name: ath_proximity_app
description: ATH PROXIMITY - GET CONNECTED
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.35.5
  flutter_local_notifications: ^15.1.0
  shared_preferences: ^2.2.1
  uuid: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
